// ============================================================
//  📸  רשימת תמונות — נוצר אוטומטית מהתמונות שלך
// ============================================================

const photos = [
  { src: "images/photo_001.jpg", caption: "נובמבר 2016" },
  { src: "images/photo_002.jpg", caption: "מרץ 2018" },
  { src: "images/photo_003.jpg", caption: "מרץ 2018" },
  { src: "images/photo_004.jpg", caption: "מרץ 2018" },
  { src: "images/photo_005.jpg", caption: "נובמבר 2018" },
  { src: "images/photo_006.jpg", caption: "יוני 2019" },
  { src: "images/photo_007.jpg", caption: "יולי 2019" },
  { src: "images/photo_008.jpg", caption: "אוגוסט 2019" },
  { src: "images/photo_009.jpg", caption: "ספטמבר 2019" },
  { src: "images/photo_010.jpg", caption: "ספטמבר 2019" },
  { src: "images/photo_011.jpg", caption: "ספטמבר 2019" },
  { src: "images/photo_012.jpg", caption: "ספטמבר 2019" },
  { src: "images/photo_013.jpg", caption: "ספטמבר 2019" },
  { src: "images/photo_014.jpg", caption: "ספטמבר 2019" },
  { src: "images/photo_015.jpg", caption: "ספטמבר 2019" },
  { src: "images/photo_016.jpg", caption: "אוקטובר 2019" },
  { src: "images/photo_017.jpg", caption: "אוקטובר 2019" },
  { src: "images/photo_018.jpg", caption: "יולי 2020" },
  { src: "images/photo_019.jpg", caption: "יולי 2020" },
  { src: "images/photo_020.jpg", caption: "יולי 2020" },
  { src: "images/photo_021.jpg", caption: "ספטמבר 2020" },
  { src: "images/photo_022.jpg", caption: "פברואר 2021" },
  { src: "images/photo_023.jpg", caption: "מאי 2021" },
  { src: "images/photo_024.jpg", caption: "אוגוסט 2021" },
  { src: "images/photo_025.jpg", caption: "אוגוסט 2021" },
  { src: "images/photo_026.jpg", caption: "ספטמבר 2021" },
  { src: "images/photo_027.jpg", caption: "ספטמבר 2021" },
  { src: "images/photo_028.jpg", caption: "ספטמבר 2021" },
  { src: "images/photo_029.jpg", caption: "אוקטובר 2021" },
  { src: "images/photo_030.jpg", caption: "אוקטובר 2021" },
  { src: "images/photo_031.jpg", caption: "נובמבר 2021" },
  { src: "images/photo_032.jpg", caption: "דצמבר 2021" },
  { src: "images/photo_033.jpg", caption: "דצמבר 2021" },
  { src: "images/photo_034.jpg", caption: "דצמבר 2021" },
  { src: "images/photo_035.jpg", caption: "דצמבר 2021" },
  { src: "images/photo_036.jpg", caption: "פברואר 2022" },
  { src: "images/photo_037.jpg", caption: "פברואר 2022" },
  { src: "images/photo_038.jpg", caption: "מרץ 2022" },
  { src: "images/photo_039.jpg", caption: "מרץ 2022" },
  { src: "images/photo_040.jpg", caption: "מרץ 2022" },
  { src: "images/photo_041.jpg", caption: "מרץ 2022" },
  { src: "images/photo_042.jpg", caption: "אפריל 2022" },
  { src: "images/photo_043.jpg", caption: "יוני 2022" },
  { src: "images/photo_044.jpg", caption: "יוני 2022" },
  { src: "images/photo_045.jpg", caption: "יוני 2022" },
  { src: "images/photo_046.jpg", caption: "יוני 2022" },
  { src: "images/photo_047.jpg", caption: "יוני 2022" },
  { src: "images/photo_048.jpg", caption: "יוני 2022" },
  { src: "images/photo_049.jpg", caption: "ספטמבר 2022" },
  { src: "images/photo_050.jpg", caption: "ספטמבר 2022" },
  { src: "images/photo_051.jpg", caption: "ספטמבר 2022" },
  { src: "images/photo_052.jpg", caption: "ספטמבר 2022" },
  { src: "images/photo_053.jpg", caption: "אוקטובר 2022" },
  { src: "images/photo_054.jpg", caption: "מרץ 2024" },
  { src: "images/photo_055.jpg", caption: "מרץ 2024" },
  { src: "images/photo_056.jpg", caption: "מרץ 2024" },
  { src: "images/photo_057.jpg", caption: "מרץ 2024" },
  { src: "images/photo_058.jpg", caption: "מרץ 2024" },
  { src: "images/photo_059.jpg", caption: "מאי 2024" },
  { src: "images/photo_060.jpg", caption: "מאי 2024" },
  { src: "images/photo_061.jpg", caption: "מאי 2024" },
  { src: "images/photo_062.jpg", caption: "יוני 2024" },
  { src: "images/photo_063.jpg", caption: "יוני 2024" },
  { src: "images/photo_064.jpg", caption: "יוני 2024" },
  { src: "images/photo_065.jpg", caption: "יוני 2024" },
  { src: "images/photo_066.jpg", caption: "יוני 2024" },
  { src: "images/photo_067.jpg", caption: "יולי 2024" },
  { src: "images/photo_068.jpg", caption: "אוקטובר 2024" },
  { src: "images/photo_069.jpg", caption: "יוני 2025" },
  { src: "images/photo_070.jpg", caption: "יולי 2025" },
  { src: "images/photo_071.jpg", caption: "ספטמבר 2025" },
  { src: "images/photo_072.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_073.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_074.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_075.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_076.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_077.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_078.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_079.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_080.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_081.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_082.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_083.jpg", caption: "ינואר 2026" },
  { src: "images/photo_084.jpg", caption: "פברואר 2026" },
  { src: "images/photo_085.jpg", caption: "פברואר 2026" },
  { src: "images/photo_086.jpg", caption: "פברואר 2026" },
  { src: "images/photo_087.jpg", caption: "פברואר 2026" },
  { src: "images/photo_088.jpg", caption: "פברואר 2026" },
  { src: "images/photo_089.jpg", caption: "מרץ 2026" },
  { src: "images/photo_090.jpg", caption: "ביחד" },
  { src: "images/photo_091.jpg", caption: "ביחד" },
  { src: "images/photo_092.jpg", caption: "ביחד" },
  { src: "images/photo_093.jpg", caption: "ביחד" },
  { src: "images/photo_094.jpg", caption: "ביחד" },
  { src: "images/photo_095.jpg", caption: "ביחד" },
  { src: "images/photo_096.jpg", caption: "ביחד" },
  { src: "images/photo_097.jpg", caption: "ביחד" },
  { src: "images/photo_098.jpg", caption: "ביחד" },
  { src: "images/photo_099.jpg", caption: "ביחד" },
  { src: "images/photo_100.jpg", caption: "ביחד" },
  { src: "images/photo_101.jpg", caption: "ביחד" },
  { src: "images/photo_102.jpg", caption: "ביחד" },
  { src: "images/photo_103.jpg", caption: "ביחד" },
  { src: "images/photo_104.jpg", caption: "ביחד" },
  { src: "images/photo_105.jpg", caption: "ביחד" },
  { src: "images/photo_106.jpg", caption: "ביחד" },
  { src: "images/photo_107.jpg", caption: "ביחד" },
  { src: "images/photo_108.jpg", caption: "ביחד" },
  { src: "images/photo_109.jpg", caption: "ביחד" },
  { src: "images/photo_110.jpg", caption: "ביחד" },
  { src: "images/photo_111.jpg", caption: "ביחד" },
  { src: "images/photo_112.jpg", caption: "ביחד" },
  { src: "images/photo_113.jpg", caption: "נובמבר 2016" },
  { src: "images/photo_114.jpg", caption: "פברואר 2017" },
  { src: "images/photo_115.jpg", caption: "מרץ 2017" },
  { src: "images/photo_116.jpg", caption: "יוני 2017" },
  { src: "images/photo_117.jpg", caption: "אפריל 2018" },
  { src: "images/photo_118.jpg", caption: "יוני 2018" },
  { src: "images/photo_119.jpg", caption: "אוקטובר 2018" },
  { src: "images/photo_120.jpg", caption: "נובמבר 2018" },
  { src: "images/photo_121.jpg", caption: "נובמבר 2018" },
  { src: "images/photo_122.jpg", caption: "מרץ 2019" },
  { src: "images/photo_123.jpg", caption: "מרץ 2019" },
  { src: "images/photo_124.jpg", caption: "יולי 2019" },
  { src: "images/photo_125.jpg", caption: "פברואר 2020" },
  { src: "images/photo_126.jpg", caption: "פברואר 2020" },
  { src: "images/photo_127.jpg", caption: "מרץ 2020" },
  { src: "images/photo_128.jpg", caption: "יוני 2020" },
  { src: "images/photo_129.jpg", caption: "אוגוסט 2024" },
  { src: "images/photo_130.jpg", caption: "אוגוסט 2024" },
  { src: "images/photo_131.jpg", caption: "נובמבר 2024" },
  { src: "images/photo_132.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_133.jpg", caption: "אוקטובר 2025" },
  { src: "images/photo_134.jpg", caption: "מרץ 2026" },
  { src: "images/photo_135.jpg", caption: "מרץ 2026" },
  { src: "images/photo_136.jpg", caption: "ביחד" },
  { src: "images/photo_137.jpg", caption: "ביחד" },
  { src: "images/photo_138.jpg", caption: "ביחד" },
  { src: "images/photo_139.jpg", caption: "ביחד" },
  { src: "images/photo_140.jpg", caption: "ביחד" },
  { src: "images/photo_141.jpg", caption: "ביחד" },
  { src: "images/photo_142.jpg", caption: "ביחד" },
  { src: "images/photo_143.jpg", caption: "ביחד" },
  { src: "images/photo_144.jpg", caption: "ביחד" },
  { src: "images/photo_145.jpg", caption: "ביחד" },
  { src: "images/photo_146.jpg", caption: "ביחד" },
  { src: "images/photo_147.jpg", caption: "ביחד" },
  { src: "images/photo_148.jpg", caption: "ביחד" },
  { src: "images/photo_149.jpg", caption: "ביחד" },
  { src: "images/photo_150.jpg", caption: "ביחד" },
  { src: "images/photo_151.jpg", caption: "ביחד" },
  { src: "images/photo_152.jpg", caption: "ביחד" },
  { src: "images/photo_153.jpg", caption: "ביחד" },
  { src: "images/photo_154.jpg", caption: "ביחד" },
  { src: "images/photo_155.jpg", caption: "ביחד" },
  { src: "images/photo_156.jpg", caption: "ביחד" },
  { src: "images/photo_157.jpg", caption: "ביחד" },
  { src: "images/photo_158.jpg", caption: "ביחד" },
  { src: "images/photo_159.jpg", caption: "ביחד" },
  { src: "images/photo_160.jpg", caption: "ביחד" },
  { src: "images/photo_161.jpg", caption: "ביחד" },
  { src: "images/photo_162.jpg", caption: "ביחד" },
  { src: "images/photo_163.jpg", caption: "ביחד" },
  { src: "images/photo_164.jpg", caption: "ביחד" },
  { src: "images/photo_165.jpg", caption: "ביחד" },
  { src: "images/photo_166.jpg", caption: "ביחד" },
  { src: "images/photo_167.jpg", caption: "ביחד" },
  { src: "images/photo_168.jpg", caption: "ביחד" },
  { src: "images/photo_169.jpg", caption: "ביחד" },
  { src: "images/photo_170.jpg", caption: "ביחד" },
  { src: "images/photo_171.jpg", caption: "ביחד" },
  { src: "images/photo_172.jpg", caption: "ביחד" },
  { src: "images/photo_173.jpg", caption: "ביחד" },
  { src: "images/photo_174.jpg", caption: "ביחד" },
  { src: "images/photo_175.jpg", caption: "ביחד" },
  { src: "images/photo_176.jpg", caption: "ביחד" },
  { src: "images/photo_177.jpg", caption: "ביחד" },
  { src: "images/photo_178.jpg", caption: "ביחד" },
  { src: "images/photo_179.jpg", caption: "ביחד" },
  { src: "images/photo_180.jpg", caption: "ביחד" },
  { src: "images/photo_181.jpg", caption: "ביחד" },
  { src: "images/photo_182.jpg", caption: "ביחד" },
  { src: "images/photo_183.jpg", caption: "ביחד" },
  { src: "images/photo_184.jpg", caption: "ביחד" },
  { src: "images/photo_185.jpg", caption: "ביחד" },
  { src: "images/photo_186.jpg", caption: "ביחד" },
  { src: "images/photo_187.jpg", caption: "ביחד" },
  { src: "images/photo_188.jpg", caption: "ביחד" },
];

// תמונות לסקשנים (index בתוך מערך photos)
const HERO_PHOTO     = photos[183];
const LETTER_PHOTO   = photos[0];
const SECTION_PHOTOS = [
  photos[9],  // ספטמבר 2019
  photos[37],  // מרץ 2022
  photos[75],  // אוקטובר 2025
  photos[112],  // נובמבר 2016
  photos[150],  // ביחד
  photos[187],  // ביחד
];